### ISSUE TITLE
Api parece estar quebrada

### ISSUE THREAD

**Issue by josevitorheringer** [napunda/Animedle#1]
Primeira vez jogando e percebi que nenhum dos animes listados são dados como a resposta correta.

Fiz um script pra fazer requisições diretas pra api passando o animeId, como é feito normalmente, entretanto, nenhum retornou como verdadeiro. Testei do id 1 ao 1500, mesmo sabendo que a listagem ia até o 269 (com exceção de alguns aleatórios no meio que pareciam ter sido apagados dos registros)

O repositório da Api que encontrei parecia estar desatualizado, visto que estava escrito em javascript e os retornos do serviço em produção pareciam ser de origem do php, então nào consegui investigar o que podia estar acontecendo.

Endpoint das requisições feitas no script: `https://www.animedle.com/api/play/validate-answer` passando o animeId via form-data (usando como exemplo o request que o front faz)

Tentei usar também o endpoint `https://www.animedle.com/api/anime/{id}` para conseguir ter mais dados, mas todos os ids passados retornavam os parâmetros como falso, sendo o único parâmetro verdadeiro o "finished" para animes que ainda não foram finalizados (provavelmente tá tratando o anime correto como algo genérico com valores default).

gostei muito da ideia do projeto e espero que tenha mais atualizações =)

**Comment by napunda** [comment]
Olá, muito obrigado pelo feedback meu amigo.
Sim, infelizmente por falta de tempo não estou atualizando o cadastro de
animes no site(o fato das dicas serem screenshots e cenas do anime gastam bastante tempo para criar, essa foi a dificuldade haha).
A API não está quebrando exatamente, o que acontece é que
todos os animes que tem dicas cadastras já estrearam e o meu script de
gerar o anime diário apenas considera animes que têm essas dicas.
O mais cedo que der vou aumentar a lista de animes e melhorar esse tratamento de erro
para o jogo não ficar disponível assim quando não tem anime diário.

Tenha um bom dia e abraços.

**Comment by josevitorheringer** [comment]
Entendii!

Faz sentido haha Vou fechar a issue aqui então. 

Sucesso pra ti, meu querido e tenha uma ótima semana
